import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { StudentAdmission } from '@/pages/students/admission/types'
import { useClassStore } from './classStore'

function normalizeClassName(raw: string, classes: { id: string; name: string }[]): string {
  if (!raw) return raw
  if (/^\d+$/.test(raw)) {
    const num = raw.replace(/^0+/, '')
    const match = classes.find((cls) => cls.name === `Class ${num}`)
    return match ? match.name : raw
  }
  return raw
}

// Sample data for testing - 50 students
const sampleStudents: StudentAdmission[] = [
  {
    id: 'ET-2026-1001',
    createdAt: '2026-05-01',
    updatedAt: '2026-05-01',
    status: 'approved',
    approvedAt: '2026-05-01',
    photo: '',
    nameEn: 'Arafat Hossain',
    nameBn: 'আরাফাত হোসাইন',
    dob: '2016-02-02',
    gender: 'Male',
    bloodGroup: 'A-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01711-00001',
    email: 'arafat.hossain@mail.com',
    class: '1',
    section: 'A',
    roll: '01',
    academicYear: '2025-26',
    previousSchool: 'Govt Model School',
    admissionDate: '2026-05-01',
    presentAddress: 'Chittagong Main Road, Block-A',
    permanentAddress: 'Chittagong Sadar',
    district: 'Chittagong',
    fatherNameEn: 'Md. Hossain',
    fatherNameBn: 'মোঃ হোসাইন',
    fatherOccupation: 'Business',
    fatherPhone: '01722-00001',
    fatherNid: '1000010000',
    motherNameEn: 'Arafat Begum',
    motherNameBn: 'আরাফাত বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01732-00001',
    motherNid: '2000010000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1002',
    createdAt: '2026-05-02',
    updatedAt: '2026-05-02',
    status: 'approved',
    approvedAt: '2026-05-02',
    photo: '',
    nameEn: 'Sumaiya Akter',
    nameBn: 'সুমাইয়া আক্তার',
    dob: '2016-03-03',
    gender: 'Female',
    bloodGroup: 'B+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01711-00002',
    email: 'sumaiya.akter@mail.com',
    class: '2',
    section: 'B',
    roll: '02',
    academicYear: '2025-26',
    previousSchool: 'Ideal Academy',
    admissionDate: '2026-05-02',
    presentAddress: 'Sylhet Main Road, Block-B',
    permanentAddress: 'Sylhet Uttar',
    district: 'Sylhet',
    fatherNameEn: 'Mr. Akter',
    fatherNameBn: 'শেখ আক্তার',
    fatherOccupation: 'Service',
    fatherPhone: '01723-00002',
    fatherNid: '1000020000',
    motherNameEn: 'Sumaiya Begum',
    motherNameBn: 'সুমাইয়া বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01733-00002',
    motherNid: '2000020000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1003',
    createdAt: '2026-05-03',
    updatedAt: '2026-05-03',
    status: 'approved',
    approvedAt: '2026-05-03',
    photo: '',
    nameEn: 'Shanto Khan',
    nameBn: 'সান্তো খান',
    dob: '2016-04-04',
    gender: 'Male',
    bloodGroup: 'B-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01712-00003',
    email: 'shanto.khan@mail.com',
    class: '3',
    section: 'C',
    roll: '03',
    academicYear: '2025-26',
    previousSchool: 'Sunrise School',
    admissionDate: '2026-05-03',
    presentAddress: 'Rajshahi Main Road, Block-C',
    permanentAddress: 'Rajshahi Dakshin',
    district: 'Rajshahi',
    fatherNameEn: 'Sheikh Khan',
    fatherNameBn: 'মাওলানা খান',
    fatherOccupation: 'Teacher',
    fatherPhone: '01724-00003',
    fatherNid: '1000030000',
    motherNameEn: 'Shanto Begum',
    motherNameBn: 'সান্তো বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01734-00003',
    motherNid: '2000030000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1004',
    createdAt: '2026-05-04',
    updatedAt: '2026-05-04',
    status: 'approved',
    approvedAt: '2026-05-04',
    photo: '',
    nameEn: 'Taslima Begum',
    nameBn: 'তাসলিমা বেগম',
    dob: '2016-05-05',
    gender: 'Female',
    bloodGroup: 'O+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01712-00004',
    email: 'taslima.begum@mail.com',
    class: '4',
    section: 'D',
    roll: '04',
    academicYear: '2025-26',
    previousSchool: 'Bangladesh International School',
    admissionDate: '2026-05-04',
    presentAddress: 'Khulna Main Road, Block-D',
    permanentAddress: 'Khulna Purba',
    district: 'Khulna',
    fatherNameEn: 'Moulana Begum',
    fatherNameBn: 'মোঃ বেগম',
    fatherOccupation: 'Engineer',
    fatherPhone: '01725-00004',
    fatherNid: '1000040000',
    motherNameEn: 'Taslima Begum',
    motherNameBn: 'তাসলিমা বেগম',
    motherOccupation: 'Service',
    motherPhone: '01735-00004',
    motherNid: '2000040000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1005',
    createdAt: '2026-05-05',
    updatedAt: '2026-05-05',
    status: 'approved',
    approvedAt: '2026-05-05',
    photo: '',
    nameEn: 'Rakib Hasan',
    nameBn: 'রাকিব হাসান',
    dob: '2016-06-06',
    gender: 'Male',
    bloodGroup: 'O-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01712-00005',
    email: 'rakib.hasan@mail.com',
    class: '5',
    section: 'A',
    roll: '05',
    academicYear: '2025-26',
    previousSchool: 'Modern High School',
    admissionDate: '2026-05-05',
    presentAddress: 'Barisal Main Road, Block-E',
    permanentAddress: 'Barisal Pashchim',
    district: 'Barisal',
    fatherNameEn: 'Md. Hasan',
    fatherNameBn: 'শেখ হাসান',
    fatherOccupation: 'Doctor',
    fatherPhone: '01726-00005',
    fatherNid: '1000050000',
    motherNameEn: 'Rakib Begum',
    motherNameBn: 'রাকিব বেগম',
    motherOccupation: 'Business',
    motherPhone: '01736-00005',
    motherNid: '2000050000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1006',
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
    status: 'approved',
    approvedAt: '2026-05-06',
    photo: '',
    nameEn: 'Nusrat Jahan',
    nameBn: 'নুসরাত জাহান',
    dob: '2015-07-07',
    gender: 'Female',
    bloodGroup: 'AB+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01713-00006',
    email: 'nusrat.jahan@mail.com',
    class: '6',
    section: 'B',
    roll: '06',
    academicYear: '2025-26',
    previousSchool: 'Oxford International School',
    admissionDate: '2026-05-06',
    presentAddress: 'Rangpur Main Road, Block-F',
    permanentAddress: 'Rangpur Sadar',
    district: 'Rangpur',
    fatherNameEn: 'Mr. Jahan',
    fatherNameBn: 'মাওলানা জাহান',
    fatherOccupation: 'Lawyer',
    fatherPhone: '01727-00006',
    fatherNid: '1000060000',
    motherNameEn: 'Nusrat Begum',
    motherNameBn: 'নুসরাত বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01737-00006',
    motherNid: '2000060000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1007',
    createdAt: '2026-05-07',
    updatedAt: '2026-05-07',
    status: 'approved',
    approvedAt: '2026-05-07',
    photo: '',
    nameEn: 'Sohel Rana',
    nameBn: 'সোহেল রানা',
    dob: '2015-08-08',
    gender: 'Male',
    bloodGroup: 'AB-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01713-00007',
    email: 'sohel.rana@mail.com',
    class: '7',
    section: 'C',
    roll: '07',
    academicYear: '2025-26',
    previousSchool: 'South Point School',
    admissionDate: '2026-05-07',
    presentAddress: 'Mymensingh Main Road, Block-G',
    permanentAddress: 'Mymensingh Uttar',
    district: 'Mymensingh',
    fatherNameEn: 'Sheikh Rana',
    fatherNameBn: 'মোঃ রানা',
    fatherOccupation: 'Farmer',
    fatherPhone: '01728-00007',
    fatherNid: '1000070000',
    motherNameEn: 'Sohel Begum',
    motherNameBn: 'সোহেল বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01738-00007',
    motherNid: '2000070000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1008',
    createdAt: '2026-05-08',
    updatedAt: '2026-05-08',
    status: 'approved',
    approvedAt: '2026-05-08',
    photo: '',
    nameEn: 'Mim Khatun',
    nameBn: 'মিম খাতুন',
    dob: '2015-09-09',
    gender: 'Female',
    bloodGroup: 'A+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01713-00008',
    email: 'mim.khatun@mail.com',
    class: '8',
    section: 'D',
    roll: '08',
    academicYear: '2025-26',
    previousSchool: 'Green Valley School',
    admissionDate: '2026-05-08',
    presentAddress: 'Comilla Main Road, Block-H',
    permanentAddress: 'Comilla Dakshin',
    district: 'Comilla',
    fatherNameEn: 'Moulana Khatun',
    fatherNameBn: 'শেখ খাতুন',
    fatherOccupation: 'Govt Employee',
    fatherPhone: '01729-00008',
    fatherNid: '1000080000',
    motherNameEn: 'Mim Begum',
    motherNameBn: 'মিম বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01739-00008',
    motherNid: '2000080000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1009',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
    status: 'approved',
    approvedAt: '2026-05-09',
    photo: '',
    nameEn: 'Tanvir Ahammed',
    nameBn: 'তানভীর আহাম্মেদ',
    dob: '2015-10-10',
    gender: 'Male',
    bloodGroup: 'A-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01714-00009',
    email: 'tanvir.ahammed@mail.com',
    class: '9',
    section: 'A',
    roll: '09',
    academicYear: '2025-26',
    previousSchool: 'Dhaka Public School',
    admissionDate: '2026-05-09',
    presentAddress: 'Bogra Main Road, Block-I',
    permanentAddress: 'Bogra Purba',
    district: 'Bogra',
    fatherNameEn: 'Md. Ahammed',
    fatherNameBn: 'মাওলানা আহাম্মেদ',
    fatherOccupation: 'Business',
    fatherPhone: '01730-00009',
    fatherNid: '1000090000',
    motherNameEn: 'Tanvir Begum',
    motherNameBn: 'তানভীর বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01740-00009',
    motherNid: '2000090000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1010',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
    status: 'approved',
    approvedAt: '2026-05-10',
    photo: '',
    nameEn: 'Jannatul Ferdous',
    nameBn: 'জান্নাতুল ফেরদৌস',
    dob: '2015-11-11',
    gender: 'Female',
    bloodGroup: 'B+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01714-00010',
    email: 'jannatul.ferdous@mail.com',
    class: '10',
    section: 'B',
    roll: '10',
    academicYear: '2025-26',
    previousSchool: 'Scholastica',
    admissionDate: '2026-05-10',
    presentAddress: 'Jessore Main Road, Block-J',
    permanentAddress: 'Jessore Pashchim',
    district: 'Jessore',
    fatherNameEn: 'Mr. Ferdous',
    fatherNameBn: 'মোঃ ফেরদৌস',
    fatherOccupation: 'Service',
    fatherPhone: '01731-00010',
    fatherNid: '1000100000',
    motherNameEn: 'Jannatul Begum',
    motherNameBn: 'জান্নাতুল বেগম',
    motherOccupation: 'Service',
    motherPhone: '01741-00010',
    motherNid: '2000100000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1011',
    createdAt: '2026-06-11',
    updatedAt: '2026-06-11',
    status: 'approved',
    approvedAt: '2026-06-11',
    photo: '',
    nameEn: 'Mehedi Hasan',
    nameBn: 'মেহেদী হাসান',
    dob: '2015-12-12',
    gender: 'Male',
    bloodGroup: 'B-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01714-00011',
    email: 'mehedi.hasan@mail.com',
    class: '1',
    section: 'C',
    roll: '11',
    academicYear: '2025-26',
    previousSchool: 'Govt Model School',
    admissionDate: '2026-06-11',
    presentAddress: 'Dinajpur Main Road, Block-K',
    permanentAddress: 'Dinajpur Sadar',
    district: 'Dinajpur',
    fatherNameEn: 'Sheikh Hasan',
    fatherNameBn: 'শেখ হাসান',
    fatherOccupation: 'Teacher',
    fatherPhone: '01732-00011',
    fatherNid: '1000110000',
    motherNameEn: 'Mehedi Begum',
    motherNameBn: 'মেহেদী বেগম',
    motherOccupation: 'Business',
    motherPhone: '01742-00011',
    motherNid: '2000110000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1012',
    createdAt: '2026-06-12',
    updatedAt: '2026-06-12',
    status: 'approved',
    approvedAt: '2026-06-12',
    photo: '',
    nameEn: 'Sadia Islam',
    nameBn: 'সাদিয়া ইসলাম',
    dob: '2014-01-13',
    gender: 'Female',
    bloodGroup: 'O+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01715-00012',
    email: 'sadia.islam@mail.com',
    class: '2',
    section: 'D',
    roll: '12',
    academicYear: '2025-26',
    previousSchool: 'Ideal Academy',
    admissionDate: '2026-06-12',
    presentAddress: 'Pabna Main Road, Block-L',
    permanentAddress: 'Pabna Uttar',
    district: 'Pabna',
    fatherNameEn: 'Moulana Islam',
    fatherNameBn: 'মাওলানা ইসলাম',
    fatherOccupation: 'Engineer',
    fatherPhone: '01733-00012',
    fatherNid: '1000120000',
    motherNameEn: 'Sadia Begum',
    motherNameBn: 'সাদিয়া বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01743-00012',
    motherNid: '2000120000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1013',
    createdAt: '2026-06-13',
    updatedAt: '2026-06-13',
    status: 'approved',
    approvedAt: '2026-06-13',
    photo: '',
    nameEn: 'Rubel Miah',
    nameBn: 'রুবেল মিয়া',
    dob: '2014-02-14',
    gender: 'Male',
    bloodGroup: 'O-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01715-00013',
    email: 'rubel.miah@mail.com',
    class: '3',
    section: 'A',
    roll: '13',
    academicYear: '2025-26',
    previousSchool: 'Sunrise School',
    admissionDate: '2026-06-13',
    presentAddress: 'Narayanganj Main Road, Block-M',
    permanentAddress: 'Narayanganj Dakshin',
    district: 'Narayanganj',
    fatherNameEn: 'Md. Miah',
    fatherNameBn: 'মোঃ মিয়া',
    fatherOccupation: 'Doctor',
    fatherPhone: '01734-00013',
    fatherNid: '1000130000',
    motherNameEn: 'Rubel Begum',
    motherNameBn: 'রুবেল বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01744-00013',
    motherNid: '2000130000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1014',
    createdAt: '2026-06-14',
    updatedAt: '2026-06-14',
    status: 'approved',
    approvedAt: '2026-06-14',
    photo: '',
    nameEn: 'Resma Akhter',
    nameBn: 'রেসমা আখতার',
    dob: '2014-03-15',
    gender: 'Female',
    bloodGroup: 'AB+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01715-00014',
    email: 'resma.akhter@mail.com',
    class: '4',
    section: 'B',
    roll: '14',
    academicYear: '2025-26',
    previousSchool: 'Bangladesh International School',
    admissionDate: '2026-06-14',
    presentAddress: 'Gazipur Main Road, Block-N',
    permanentAddress: 'Gazipur Purba',
    district: 'Gazipur',
    fatherNameEn: 'Mr. Akhter',
    fatherNameBn: 'শেখ আখতার',
    fatherOccupation: 'Lawyer',
    fatherPhone: '01735-00014',
    fatherNid: '1000140000',
    motherNameEn: 'Resma Begum',
    motherNameBn: 'রেসমা বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01745-00014',
    motherNid: '2000140000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1015',
    createdAt: '2026-06-15',
    updatedAt: '2026-06-15',
    status: 'approved',
    approvedAt: '2026-06-15',
    photo: '',
    nameEn: 'Naimul Islam',
    nameBn: 'নাইমুল ইসলাম',
    dob: '2014-04-16',
    gender: 'Male',
    bloodGroup: 'AB-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01716-00015',
    email: 'naimul.islam@mail.com',
    class: '5',
    section: 'C',
    roll: '15',
    academicYear: '2025-26',
    previousSchool: 'Modern High School',
    admissionDate: '2026-06-15',
    presentAddress: 'Dhaka Main Road, Block-O',
    permanentAddress: 'Dhaka Pashchim',
    district: 'Dhaka',
    fatherNameEn: 'Sheikh Islam',
    fatherNameBn: 'মাওলানা ইসলাম',
    fatherOccupation: 'Farmer',
    fatherPhone: '01736-00015',
    fatherNid: '1000150000',
    motherNameEn: 'Naimul Begum',
    motherNameBn: 'নাইমুল বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01746-00015',
    motherNid: '2000150000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1016',
    createdAt: '2026-06-16',
    updatedAt: '2026-06-16',
    status: 'approved',
    approvedAt: '2026-06-16',
    photo: '',
    nameEn: 'Sraboni Das',
    nameBn: 'শ্রাবণী দাস',
    dob: '2014-05-17',
    gender: 'Female',
    bloodGroup: 'A+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01716-00016',
    email: 'sraboni.das@mail.com',
    class: '6',
    section: 'D',
    roll: '16',
    academicYear: '2025-26',
    previousSchool: 'Oxford International School',
    admissionDate: '2026-06-16',
    presentAddress: 'Chittagong Main Road, Block-P',
    permanentAddress: 'Chittagong Sadar',
    district: 'Chittagong',
    fatherNameEn: 'Moulana Das',
    fatherNameBn: 'মোঃ দাস',
    fatherOccupation: 'Govt Employee',
    fatherPhone: '01737-00016',
    fatherNid: '1000160000',
    motherNameEn: 'Sraboni Begum',
    motherNameBn: 'শ্রাবণী বেগম',
    motherOccupation: 'Service',
    motherPhone: '01747-00016',
    motherNid: '2000160000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1017',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
    status: 'approved',
    approvedAt: '2026-06-17',
    photo: '',
    nameEn: 'Mizanur Rahman',
    nameBn: 'মিজানুর রহমান',
    dob: '2014-06-18',
    gender: 'Male',
    bloodGroup: 'A-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01716-00017',
    email: 'mizanur.rahman@mail.com',
    class: '7',
    section: 'A',
    roll: '17',
    academicYear: '2025-26',
    previousSchool: 'South Point School',
    admissionDate: '2026-06-17',
    presentAddress: 'Sylhet Main Road, Block-Q',
    permanentAddress: 'Sylhet Uttar',
    district: 'Sylhet',
    fatherNameEn: 'Md. Rahman',
    fatherNameBn: 'শেখ রহমান',
    fatherOccupation: 'Business',
    fatherPhone: '01738-00017',
    fatherNid: '1000170000',
    motherNameEn: 'Mizanur Begum',
    motherNameBn: 'মিজানুর বেগম',
    motherOccupation: 'Business',
    motherPhone: '01748-00017',
    motherNid: '2000170000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1018',
    createdAt: '2026-06-18',
    updatedAt: '2026-06-18',
    status: 'approved',
    approvedAt: '2026-06-18',
    photo: '',
    nameEn: 'Sharmin Sultana',
    nameBn: 'শারমিন সুলতানা',
    dob: '2013-07-19',
    gender: 'Female',
    bloodGroup: 'B+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01717-00018',
    email: 'sharmin.sultana@mail.com',
    class: '8',
    section: 'B',
    roll: '18',
    academicYear: '2025-26',
    previousSchool: 'Green Valley School',
    admissionDate: '2026-06-18',
    presentAddress: 'Rajshahi Main Road, Block-R',
    permanentAddress: 'Rajshahi Dakshin',
    district: 'Rajshahi',
    fatherNameEn: 'Mr. Sultana',
    fatherNameBn: 'মাওলানা সুলতানা',
    fatherOccupation: 'Service',
    fatherPhone: '01739-00018',
    fatherNid: '1000180000',
    motherNameEn: 'Sharmin Begum',
    motherNameBn: 'শারমিন বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01749-00018',
    motherNid: '2000180000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1019',
    createdAt: '2026-06-19',
    updatedAt: '2026-06-19',
    status: 'approved',
    approvedAt: '2026-06-19',
    photo: '',
    nameEn: 'Al Amin',
    nameBn: 'আল আমিন',
    dob: '2013-08-20',
    gender: 'Male',
    bloodGroup: 'B-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01717-00019',
    email: 'al.amin@mail.com',
    class: '9',
    section: 'C',
    roll: '19',
    academicYear: '2025-26',
    previousSchool: 'Dhaka Public School',
    admissionDate: '2026-06-19',
    presentAddress: 'Khulna Main Road, Block-S',
    permanentAddress: 'Khulna Purba',
    district: 'Khulna',
    fatherNameEn: 'Sheikh Amin',
    fatherNameBn: 'মোঃ আমিন',
    fatherOccupation: 'Teacher',
    fatherPhone: '01740-00019',
    fatherNid: '1000190000',
    motherNameEn: 'Al Begum',
    motherNameBn: 'আল বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01750-00019',
    motherNid: '2000190000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1020',
    createdAt: '2026-06-20',
    updatedAt: '2026-06-20',
    status: 'approved',
    approvedAt: '2026-06-20',
    photo: '',
    nameEn: 'Marjia Khatun',
    nameBn: 'মার্জিয়া খাতুন',
    dob: '2013-09-21',
    gender: 'Female',
    bloodGroup: 'O+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01717-00020',
    email: 'marjia.khatun@mail.com',
    class: '10',
    section: 'D',
    roll: '20',
    academicYear: '2025-26',
    previousSchool: 'Scholastica',
    admissionDate: '2026-06-20',
    presentAddress: 'Barisal Main Road, Block-T',
    permanentAddress: 'Barisal Pashchim',
    district: 'Barisal',
    fatherNameEn: 'Moulana Khatun',
    fatherNameBn: 'শেখ খাতুন',
    fatherOccupation: 'Engineer',
    fatherPhone: '01741-00020',
    fatherNid: '1000200000',
    motherNameEn: 'Marjia Begum',
    motherNameBn: 'মার্জিয়া বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01751-00020',
    motherNid: '2000200000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1021',
    createdAt: '2026-07-21',
    updatedAt: '2026-07-21',
    status: 'approved',
    approvedAt: '2026-07-21',
    photo: '',
    nameEn: 'Asaduzzaman',
    nameBn: 'আসাদুজ্জামান',
    dob: '2013-10-22',
    gender: 'Male',
    bloodGroup: 'O-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01718-00021',
    email: 'asaduzzaman@mail.com',
    class: '1',
    section: 'A',
    roll: '21',
    academicYear: '2025-26',
    previousSchool: 'Govt Model School',
    admissionDate: '2026-07-21',
    presentAddress: 'Rangpur Main Road, Block-U',
    permanentAddress: 'Rangpur Sadar',
    district: 'Rangpur',
    fatherNameEn: 'Md. Asaduzzaman',
    fatherNameBn: 'মাওলানা আসাদুজ্জামান',
    fatherOccupation: 'Doctor',
    fatherPhone: '01742-00021',
    fatherNid: '1000210000',
    motherNameEn: 'Asaduzzaman Begum',
    motherNameBn: 'আসাদুজ্জামান বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01752-00021',
    motherNid: '2000210000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1022',
    createdAt: '2026-07-22',
    updatedAt: '2026-07-22',
    status: 'approved',
    approvedAt: '2026-07-22',
    photo: '',
    nameEn: 'Ripa Begum',
    nameBn: 'রিপা বেগম',
    dob: '2013-11-23',
    gender: 'Female',
    bloodGroup: 'AB+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01718-00022',
    email: 'ripa.begum@mail.com',
    class: '2',
    section: 'B',
    roll: '22',
    academicYear: '2025-26',
    previousSchool: 'Ideal Academy',
    admissionDate: '2026-07-22',
    presentAddress: 'Mymensingh Main Road, Block-V',
    permanentAddress: 'Mymensingh Uttar',
    district: 'Mymensingh',
    fatherNameEn: 'Mr. Begum',
    fatherNameBn: 'মোঃ বেগম',
    fatherOccupation: 'Lawyer',
    fatherPhone: '01743-00022',
    fatherNid: '1000220000',
    motherNameEn: 'Ripa Begum',
    motherNameBn: 'রিপা বেগম',
    motherOccupation: 'Service',
    motherPhone: '01753-00022',
    motherNid: '2000220000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1023',
    createdAt: '2026-07-23',
    updatedAt: '2026-07-23',
    status: 'approved',
    approvedAt: '2026-07-23',
    photo: '',
    nameEn: 'Shahin Alam',
    nameBn: 'শাহীন আলম',
    dob: '2013-12-24',
    gender: 'Male',
    bloodGroup: 'AB-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01718-00023',
    email: 'shahin.alam@mail.com',
    class: '3',
    section: 'C',
    roll: '23',
    academicYear: '2025-26',
    previousSchool: 'Sunrise School',
    admissionDate: '2026-07-23',
    presentAddress: 'Comilla Main Road, Block-W',
    permanentAddress: 'Comilla Dakshin',
    district: 'Comilla',
    fatherNameEn: 'Sheikh Alam',
    fatherNameBn: 'শেখ আলম',
    fatherOccupation: 'Farmer',
    fatherPhone: '01744-00023',
    fatherNid: '1000230000',
    motherNameEn: 'Shahin Begum',
    motherNameBn: 'শাহীন বেগম',
    motherOccupation: 'Business',
    motherPhone: '01754-00023',
    motherNid: '2000230000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1024',
    createdAt: '2026-07-24',
    updatedAt: '2026-07-24',
    status: 'approved',
    approvedAt: '2026-07-24',
    photo: '',
    nameEn: 'Jui Rani Das',
    nameBn: 'জুই রানী দাস',
    dob: '2012-01-25',
    gender: 'Female',
    bloodGroup: 'A+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01719-00024',
    email: 'jui.rani.das@mail.com',
    class: '4',
    section: 'D',
    roll: '24',
    academicYear: '2025-26',
    previousSchool: 'Bangladesh International School',
    admissionDate: '2026-07-24',
    presentAddress: 'Bogra Main Road, Block-X',
    permanentAddress: 'Bogra Purba',
    district: 'Bogra',
    fatherNameEn: 'Moulana Rani',
    fatherNameBn: 'মাওলানা রানী',
    fatherOccupation: 'Govt Employee',
    fatherPhone: '01745-00024',
    fatherNid: '1000240000',
    motherNameEn: 'Jui Begum',
    motherNameBn: 'জুই বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01755-00024',
    motherNid: '2000240000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1025',
    createdAt: '2026-07-25',
    updatedAt: '2026-07-25',
    status: 'approved',
    approvedAt: '2026-07-25',
    photo: '',
    nameEn: 'Azizul Haque',
    nameBn: 'আজিজুল হক',
    dob: '2012-02-26',
    gender: 'Male',
    bloodGroup: 'A-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01719-00025',
    email: 'azizul.haque@mail.com',
    class: '5',
    section: 'A',
    roll: '25',
    academicYear: '2025-26',
    previousSchool: 'Modern High School',
    admissionDate: '2026-07-25',
    presentAddress: 'Jessore Main Road, Block-Y',
    permanentAddress: 'Jessore Pashchim',
    district: 'Jessore',
    fatherNameEn: 'Md. Haque',
    fatherNameBn: 'মোঃ হক',
    fatherOccupation: 'Business',
    fatherPhone: '01746-00025',
    fatherNid: '1000250000',
    motherNameEn: 'Azizul Begum',
    motherNameBn: 'আজিজুল বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01756-00025',
    motherNid: '2000250000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1026',
    createdAt: '2026-07-26',
    updatedAt: '2026-07-26',
    status: 'approved',
    approvedAt: '2026-07-26',
    photo: '',
    nameEn: 'Farzana Hoque',
    nameBn: 'ফার্জানা হক',
    dob: '2012-03-27',
    gender: 'Female',
    bloodGroup: 'B+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01719-00026',
    email: 'farzana.hoque@mail.com',
    class: '6',
    section: 'B',
    roll: '26',
    academicYear: '2025-26',
    previousSchool: 'Oxford International School',
    admissionDate: '2026-07-26',
    presentAddress: 'Dinajpur Main Road, Block-Z',
    permanentAddress: 'Dinajpur Sadar',
    district: 'Dinajpur',
    fatherNameEn: 'Mr. Hoque',
    fatherNameBn: 'শেখ হক',
    fatherOccupation: 'Service',
    fatherPhone: '01747-00026',
    fatherNid: '1000260000',
    motherNameEn: 'Farzana Begum',
    motherNameBn: 'ফার্জানা বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01757-00026',
    motherNid: '2000260000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1027',
    createdAt: '2026-07-27',
    updatedAt: '2026-07-27',
    status: 'approved',
    approvedAt: '2026-07-27',
    photo: '',
    nameEn: 'Masud Rana',
    nameBn: 'মাসুদ রানা',
    dob: '2012-04-28',
    gender: 'Male',
    bloodGroup: 'B-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01720-00027',
    email: 'masud.rana@mail.com',
    class: '7',
    section: 'C',
    roll: '27',
    academicYear: '2025-26',
    previousSchool: 'South Point School',
    admissionDate: '2026-07-27',
    presentAddress: 'Pabna Main Road, Block-A',
    permanentAddress: 'Pabna Uttar',
    district: 'Pabna',
    fatherNameEn: 'Sheikh Rana',
    fatherNameBn: 'মাওলানা রানা',
    fatherOccupation: 'Teacher',
    fatherPhone: '01748-00027',
    fatherNid: '1000270000',
    motherNameEn: 'Masud Begum',
    motherNameBn: 'মাসুদ বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01758-00027',
    motherNid: '2000270000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1028',
    createdAt: '2026-07-28',
    updatedAt: '2026-07-28',
    status: 'approved',
    approvedAt: '2026-07-28',
    photo: '',
    nameEn: 'Nazma Akhter',
    nameBn: 'নাজমা আখতার',
    dob: '2012-05-01',
    gender: 'Female',
    bloodGroup: 'O+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01720-00028',
    email: 'nazma.akhter@mail.com',
    class: '8',
    section: 'D',
    roll: '28',
    academicYear: '2025-26',
    previousSchool: 'Green Valley School',
    admissionDate: '2026-07-28',
    presentAddress: 'Narayanganj Main Road, Block-B',
    permanentAddress: 'Narayanganj Dakshin',
    district: 'Narayanganj',
    fatherNameEn: 'Moulana Akhter',
    fatherNameBn: 'মোঃ আখতার',
    fatherOccupation: 'Engineer',
    fatherPhone: '01749-00028',
    fatherNid: '1000280000',
    motherNameEn: 'Nazma Begum',
    motherNameBn: 'নাজমা বেগম',
    motherOccupation: 'Service',
    motherPhone: '01759-00028',
    motherNid: '2000280000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1029',
    createdAt: '2026-07-01',
    updatedAt: '2026-07-01',
    status: 'approved',
    approvedAt: '2026-07-01',
    photo: '',
    nameEn: 'Touhidul Islam',
    nameBn: 'তৌহিদুল ইসলাম',
    dob: '2012-06-02',
    gender: 'Male',
    bloodGroup: 'O-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01720-00029',
    email: 'touhidul.islam@mail.com',
    class: '9',
    section: 'A',
    roll: '29',
    academicYear: '2025-26',
    previousSchool: 'Dhaka Public School',
    admissionDate: '2026-07-01',
    presentAddress: 'Gazipur Main Road, Block-C',
    permanentAddress: 'Gazipur Purba',
    district: 'Gazipur',
    fatherNameEn: 'Md. Islam',
    fatherNameBn: 'শেখ ইসলাম',
    fatherOccupation: 'Doctor',
    fatherPhone: '01750-00029',
    fatherNid: '1000290000',
    motherNameEn: 'Touhidul Begum',
    motherNameBn: 'তৌহিদুল বেগম',
    motherOccupation: 'Business',
    motherPhone: '01760-00029',
    motherNid: '2000290000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1030',
    createdAt: '2026-07-02',
    updatedAt: '2026-07-02',
    status: 'approved',
    approvedAt: '2026-07-02',
    photo: '',
    nameEn: 'Roksana Parvin',
    nameBn: 'রোকসানা পারভীন',
    dob: '2011-07-03',
    gender: 'Female',
    bloodGroup: 'AB+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01721-00030',
    email: 'roksana.parvin@mail.com',
    class: '10',
    section: 'B',
    roll: '30',
    academicYear: '2025-26',
    previousSchool: 'Scholastica',
    admissionDate: '2026-07-02',
    presentAddress: 'Dhaka Main Road, Block-D',
    permanentAddress: 'Dhaka Pashchim',
    district: 'Dhaka',
    fatherNameEn: 'Mr. Parvin',
    fatherNameBn: 'মাওলানা পারভীন',
    fatherOccupation: 'Lawyer',
    fatherPhone: '01751-00030',
    fatherNid: '1000300000',
    motherNameEn: 'Roksana Begum',
    motherNameBn: 'রোকসানা বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01761-00030',
    motherNid: '2000300000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1031',
    createdAt: '2026-08-03',
    updatedAt: '2026-08-03',
    status: 'approved',
    approvedAt: '2026-08-03',
    photo: '',
    nameEn: 'Kamruzzaman',
    nameBn: 'কামরুজ্জামান',
    dob: '2011-08-04',
    gender: 'Male',
    bloodGroup: 'AB-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01721-00031',
    email: 'kamruzzaman@mail.com',
    class: '1',
    section: 'C',
    roll: '31',
    academicYear: '2025-26',
    previousSchool: 'Govt Model School',
    admissionDate: '2026-08-03',
    presentAddress: 'Chittagong Main Road, Block-E',
    permanentAddress: 'Chittagong Sadar',
    district: 'Chittagong',
    fatherNameEn: 'Sheikh Kamruzzaman',
    fatherNameBn: 'মোঃ কামরুজ্জামান',
    fatherOccupation: 'Farmer',
    fatherPhone: '01752-00031',
    fatherNid: '1000310000',
    motherNameEn: 'Kamruzzaman Begum',
    motherNameBn: 'কামরুজ্জামান বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01762-00031',
    motherNid: '2000310000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1032',
    createdAt: '2026-08-04',
    updatedAt: '2026-08-04',
    status: 'approved',
    approvedAt: '2026-08-04',
    photo: '',
    nameEn: 'Shahnaz Parvin',
    nameBn: 'শাহনাজ পারভীন',
    dob: '2011-09-05',
    gender: 'Female',
    bloodGroup: 'A+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01721-00032',
    email: 'shahnaz.parvin@mail.com',
    class: '2',
    section: 'D',
    roll: '32',
    academicYear: '2025-26',
    previousSchool: 'Ideal Academy',
    admissionDate: '2026-08-04',
    presentAddress: 'Sylhet Main Road, Block-F',
    permanentAddress: 'Sylhet Uttar',
    district: 'Sylhet',
    fatherNameEn: 'Moulana Parvin',
    fatherNameBn: 'শেখ পারভীন',
    fatherOccupation: 'Govt Employee',
    fatherPhone: '01753-00032',
    fatherNid: '1000320000',
    motherNameEn: 'Shahnaz Begum',
    motherNameBn: 'শাহনাজ বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01763-00032',
    motherNid: '2000320000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1033',
    createdAt: '2026-08-05',
    updatedAt: '2026-08-05',
    status: 'approved',
    approvedAt: '2026-08-05',
    photo: '',
    nameEn: 'Jahid Hasan',
    nameBn: 'জাহিদ হাসান',
    dob: '2011-10-06',
    gender: 'Male',
    bloodGroup: 'A-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01722-00033',
    email: 'jahid.hasan@mail.com',
    class: '3',
    section: 'A',
    roll: '33',
    academicYear: '2025-26',
    previousSchool: 'Sunrise School',
    admissionDate: '2026-08-05',
    presentAddress: 'Rajshahi Main Road, Block-G',
    permanentAddress: 'Rajshahi Dakshin',
    district: 'Rajshahi',
    fatherNameEn: 'Md. Hasan',
    fatherNameBn: 'মাওলানা হাসান',
    fatherOccupation: 'Business',
    fatherPhone: '01754-00033',
    fatherNid: '1000330000',
    motherNameEn: 'Jahid Begum',
    motherNameBn: 'জাহিদ বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01764-00033',
    motherNid: '2000330000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1034',
    createdAt: '2026-08-06',
    updatedAt: '2026-08-06',
    status: 'approved',
    approvedAt: '2026-08-06',
    photo: '',
    nameEn: 'Hasna Hena',
    nameBn: 'হাসনা হেনা',
    dob: '2011-11-07',
    gender: 'Female',
    bloodGroup: 'B+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01722-00034',
    email: 'hasna.hena@mail.com',
    class: '4',
    section: 'B',
    roll: '34',
    academicYear: '2025-26',
    previousSchool: 'Bangladesh International School',
    admissionDate: '2026-08-06',
    presentAddress: 'Khulna Main Road, Block-H',
    permanentAddress: 'Khulna Purba',
    district: 'Khulna',
    fatherNameEn: 'Mr. Hena',
    fatherNameBn: 'মোঃ হেনা',
    fatherOccupation: 'Service',
    fatherPhone: '01755-00034',
    fatherNid: '1000340000',
    motherNameEn: 'Hasna Begum',
    motherNameBn: 'হাসনা বেগম',
    motherOccupation: 'Service',
    motherPhone: '01765-00034',
    motherNid: '2000340000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1035',
    createdAt: '2026-08-07',
    updatedAt: '2026-08-07',
    status: 'approved',
    approvedAt: '2026-08-07',
    photo: '',
    nameEn: 'Shakil Ahmed',
    nameBn: 'শাকিল আহমেদ',
    dob: '2011-12-08',
    gender: 'Male',
    bloodGroup: 'B-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01722-00035',
    email: 'shakil.ahmed@mail.com',
    class: '5',
    section: 'C',
    roll: '35',
    academicYear: '2025-26',
    previousSchool: 'Modern High School',
    admissionDate: '2026-08-07',
    presentAddress: 'Barisal Main Road, Block-I',
    permanentAddress: 'Barisal Pashchim',
    district: 'Barisal',
    fatherNameEn: 'Sheikh Ahmed',
    fatherNameBn: 'শেখ আহমেদ',
    fatherOccupation: 'Teacher',
    fatherPhone: '01756-00035',
    fatherNid: '1000350000',
    motherNameEn: 'Shakil Begum',
    motherNameBn: 'শাকিল বেগম',
    motherOccupation: 'Business',
    motherPhone: '01766-00035',
    motherNid: '2000350000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1036',
    createdAt: '2026-08-08',
    updatedAt: '2026-08-08',
    status: 'pending',
    photo: '',
    nameEn: 'Rahima Akter',
    nameBn: 'রহিমা আক্তার',
    dob: '2010-01-09',
    gender: 'Female',
    bloodGroup: 'O+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01723-00036',
    email: 'rahima.akter@mail.com',
    class: '6',
    section: 'D',
    roll: '36',
    academicYear: '2025-26',
    previousSchool: 'Oxford International School',
    admissionDate: '2026-08-08',
    presentAddress: 'Rangpur Main Road, Block-J',
    permanentAddress: 'Rangpur Sadar',
    district: 'Rangpur',
    fatherNameEn: 'Moulana Akter',
    fatherNameBn: 'মাওলানা আক্তার',
    fatherOccupation: 'Engineer',
    fatherPhone: '01757-00036',
    fatherNid: '1000360000',
    motherNameEn: 'Rahima Begum',
    motherNameBn: 'রহিমা বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01767-00036',
    motherNid: '2000360000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1037',
    createdAt: '2026-08-09',
    updatedAt: '2026-08-09',
    status: 'pending',
    photo: '',
    nameEn: 'Morshed Alam',
    nameBn: 'মোর্শেদ আলম',
    dob: '2010-02-10',
    gender: 'Male',
    bloodGroup: 'O-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01723-00037',
    email: 'morshed.alam@mail.com',
    class: '7',
    section: 'A',
    roll: '37',
    academicYear: '2025-26',
    previousSchool: 'South Point School',
    admissionDate: '2026-08-09',
    presentAddress: 'Mymensingh Main Road, Block-K',
    permanentAddress: 'Mymensingh Uttar',
    district: 'Mymensingh',
    fatherNameEn: 'Md. Alam',
    fatherNameBn: 'মোঃ আলম',
    fatherOccupation: 'Doctor',
    fatherPhone: '01758-00037',
    fatherNid: '1000370000',
    motherNameEn: 'Morshed Begum',
    motherNameBn: 'মোর্শেদ বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01768-00037',
    motherNid: '2000370000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1038',
    createdAt: '2026-08-10',
    updatedAt: '2026-08-10',
    status: 'pending',
    photo: '',
    nameEn: 'Nasima Begum',
    nameBn: 'নাসিমা বেগম',
    dob: '2010-03-11',
    gender: 'Female',
    bloodGroup: 'AB+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01723-00038',
    email: 'nasima.begum@mail.com',
    class: '8',
    section: 'B',
    roll: '38',
    academicYear: '2025-26',
    previousSchool: 'Green Valley School',
    admissionDate: '2026-08-10',
    presentAddress: 'Comilla Main Road, Block-L',
    permanentAddress: 'Comilla Dakshin',
    district: 'Comilla',
    fatherNameEn: 'Mr. Begum',
    fatherNameBn: 'শেখ বেগম',
    fatherOccupation: 'Lawyer',
    fatherPhone: '01759-00038',
    fatherNid: '1000380000',
    motherNameEn: 'Nasima Begum',
    motherNameBn: 'নাসিমা বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01769-00038',
    motherNid: '2000380000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1039',
    createdAt: '2026-08-11',
    updatedAt: '2026-08-11',
    status: 'pending',
    photo: '',
    nameEn: 'Kawshar Ahmed',
    nameBn: 'কাওশার আহমেদ',
    dob: '2010-04-12',
    gender: 'Male',
    bloodGroup: 'AB-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01724-00039',
    email: 'kawshar.ahmed@mail.com',
    class: '9',
    section: 'C',
    roll: '39',
    academicYear: '2025-26',
    previousSchool: 'Dhaka Public School',
    admissionDate: '2026-08-11',
    presentAddress: 'Bogra Main Road, Block-M',
    permanentAddress: 'Bogra Purba',
    district: 'Bogra',
    fatherNameEn: 'Sheikh Ahmed',
    fatherNameBn: 'মাওলানা আহমেদ',
    fatherOccupation: 'Farmer',
    fatherPhone: '01760-00039',
    fatherNid: '1000390000',
    motherNameEn: 'Kawshar Begum',
    motherNameBn: 'কাওশার বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01770-00039',
    motherNid: '2000390000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1040',
    createdAt: '2026-08-12',
    updatedAt: '2026-08-12',
    status: 'pending',
    photo: '',
    nameEn: 'Rekha Rani',
    nameBn: 'রেখা রানী',
    dob: '2010-05-13',
    gender: 'Female',
    bloodGroup: 'A+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01724-00040',
    email: 'rekha.rani@mail.com',
    class: '10',
    section: 'D',
    roll: '40',
    academicYear: '2025-26',
    previousSchool: 'Scholastica',
    admissionDate: '2026-08-12',
    presentAddress: 'Jessore Main Road, Block-N',
    permanentAddress: 'Jessore Pashchim',
    district: 'Jessore',
    fatherNameEn: 'Moulana Rani',
    fatherNameBn: 'মোঃ রানী',
    fatherOccupation: 'Govt Employee',
    fatherPhone: '01761-00040',
    fatherNid: '1000400000',
    motherNameEn: 'Rekha Begum',
    motherNameBn: 'রেখা বেগম',
    motherOccupation: 'Service',
    motherPhone: '01771-00040',
    motherNid: '2000400000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1041',
    createdAt: '2026-09-13',
    updatedAt: '2026-09-13',
    status: 'pending',
    photo: '',
    nameEn: 'Shafiqul Islam',
    nameBn: 'সাফিকুল ইসলাম',
    dob: '2010-06-14',
    gender: 'Male',
    bloodGroup: 'A-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01724-00041',
    email: 'shafiqul.islam@mail.com',
    class: '1',
    section: 'A',
    roll: '41',
    academicYear: '2025-26',
    previousSchool: 'Govt Model School',
    admissionDate: '2026-09-13',
    presentAddress: 'Dinajpur Main Road, Block-O',
    permanentAddress: 'Dinajpur Sadar',
    district: 'Dinajpur',
    fatherNameEn: 'Md. Islam',
    fatherNameBn: 'শেখ ইসলাম',
    fatherOccupation: 'Business',
    fatherPhone: '01762-00041',
    fatherNid: '1000410000',
    motherNameEn: 'Shafiqul Begum',
    motherNameBn: 'সাফিকুল বেগম',
    motherOccupation: 'Business',
    motherPhone: '01772-00041',
    motherNid: '2000410000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1042',
    createdAt: '2026-09-14',
    updatedAt: '2026-09-14',
    status: 'pending',
    photo: '',
    nameEn: 'Sohana Akhter',
    nameBn: 'সোহানা আখতার',
    dob: '2009-07-15',
    gender: 'Female',
    bloodGroup: 'B+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01725-00042',
    email: 'sohana.akhter@mail.com',
    class: '2',
    section: 'B',
    roll: '42',
    academicYear: '2025-26',
    previousSchool: 'Ideal Academy',
    admissionDate: '2026-09-14',
    presentAddress: 'Pabna Main Road, Block-P',
    permanentAddress: 'Pabna Uttar',
    district: 'Pabna',
    fatherNameEn: 'Mr. Akhter',
    fatherNameBn: 'মাওলানা আখতার',
    fatherOccupation: 'Service',
    fatherPhone: '01763-00042',
    fatherNid: '1000420000',
    motherNameEn: 'Sohana Begum',
    motherNameBn: 'সোহানা বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01773-00042',
    motherNid: '2000420000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1043',
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
    status: 'pending',
    photo: '',
    nameEn: 'Delwar Hossain',
    nameBn: 'দেলোয়ার হোসেন',
    dob: '2009-08-16',
    gender: 'Male',
    bloodGroup: 'B-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01725-00043',
    email: 'delwar.hossain@mail.com',
    class: '3',
    section: 'C',
    roll: '43',
    academicYear: '2025-26',
    previousSchool: 'Sunrise School',
    admissionDate: '2026-09-15',
    presentAddress: 'Narayanganj Main Road, Block-Q',
    permanentAddress: 'Narayanganj Dakshin',
    district: 'Narayanganj',
    fatherNameEn: 'Sheikh Hossain',
    fatherNameBn: 'মোঃ হোসেন',
    fatherOccupation: 'Teacher',
    fatherPhone: '01764-00043',
    fatherNid: '1000430000',
    motherNameEn: 'Delwar Begum',
    motherNameBn: 'দেলোয়ার বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01774-00043',
    motherNid: '2000430000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1044',
    createdAt: '2026-09-16',
    updatedAt: '2026-09-16',
    status: 'pending',
    photo: '',
    nameEn: 'Nargis Sultana',
    nameBn: 'নারগিস সুলতানা',
    dob: '2009-09-17',
    gender: 'Female',
    bloodGroup: 'O+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01725-00044',
    email: 'nargis.sultana@mail.com',
    class: '4',
    section: 'D',
    roll: '44',
    academicYear: '2025-26',
    previousSchool: 'Bangladesh International School',
    admissionDate: '2026-09-16',
    presentAddress: 'Gazipur Main Road, Block-R',
    permanentAddress: 'Gazipur Purba',
    district: 'Gazipur',
    fatherNameEn: 'Moulana Sultana',
    fatherNameBn: 'শেখ সুলতানা',
    fatherOccupation: 'Engineer',
    fatherPhone: '01765-00044',
    fatherNid: '1000440000',
    motherNameEn: 'Nargis Begum',
    motherNameBn: 'নারগিস বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01775-00044',
    motherNid: '2000440000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1045',
    createdAt: '2026-09-17',
    updatedAt: '2026-09-17',
    status: 'pending',
    photo: '',
    nameEn: 'Golam Mostafa',
    nameBn: 'গোলাম মোস্তফা',
    dob: '2009-10-18',
    gender: 'Male',
    bloodGroup: 'O-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01726-00045',
    email: 'golam.mostafa@mail.com',
    class: '5',
    section: 'A',
    roll: '45',
    academicYear: '2025-26',
    previousSchool: 'Modern High School',
    admissionDate: '2026-09-17',
    presentAddress: 'Dhaka Main Road, Block-S',
    permanentAddress: 'Dhaka Pashchim',
    district: 'Dhaka',
    fatherNameEn: 'Md. Mostafa',
    fatherNameBn: 'মাওলানা মোস্তফা',
    fatherOccupation: 'Doctor',
    fatherPhone: '01766-00045',
    fatherNid: '1000450000',
    motherNameEn: 'Golam Begum',
    motherNameBn: 'গোলাম বেগম',
    motherOccupation: 'Doctor',
    motherPhone: '01776-00045',
    motherNid: '2000450000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1046',
    createdAt: '2026-09-18',
    updatedAt: '2026-09-18',
    status: 'rejected',
    photo: '',
    nameEn: 'Khadiza Akter',
    nameBn: 'খাদিজা আক্তার',
    dob: '2009-11-19',
    gender: 'Female',
    bloodGroup: 'AB+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01726-00046',
    email: 'khadiza.akter@mail.com',
    class: '6',
    section: 'B',
    roll: '46',
    academicYear: '2025-26',
    previousSchool: 'Oxford International School',
    admissionDate: '2026-09-18',
    presentAddress: 'Chittagong Main Road, Block-T',
    permanentAddress: 'Chittagong Sadar',
    district: 'Chittagong',
    fatherNameEn: 'Mr. Akter',
    fatherNameBn: 'মোঃ আক্তার',
    fatherOccupation: 'Lawyer',
    fatherPhone: '01767-00046',
    fatherNid: '1000460000',
    motherNameEn: 'Khadiza Begum',
    motherNameBn: 'খাদিজা বেগম',
    motherOccupation: 'Service',
    motherPhone: '01777-00046',
    motherNid: '2000460000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1047',
    createdAt: '2026-09-19',
    updatedAt: '2026-09-19',
    status: 'rejected',
    photo: '',
    nameEn: 'Ismail Hossain',
    nameBn: 'ইসমাইল হোসাইন',
    dob: '2009-12-20',
    gender: 'Male',
    bloodGroup: 'AB-',
    religion: 'Christianity / খ্রিস্টান',
    nationality: 'Bangladeshi',
    phone: '01726-00047',
    email: 'ismail.hossain@mail.com',
    class: '7',
    section: 'C',
    roll: '47',
    academicYear: '2025-26',
    previousSchool: 'South Point School',
    admissionDate: '2026-09-19',
    presentAddress: 'Sylhet Main Road, Block-U',
    permanentAddress: 'Sylhet Uttar',
    district: 'Sylhet',
    fatherNameEn: 'Sheikh Hossain',
    fatherNameBn: 'শেখ হোসাইন',
    fatherOccupation: 'Farmer',
    fatherPhone: '01768-00047',
    fatherNid: '1000470000',
    motherNameEn: 'Ismail Begum',
    motherNameBn: 'ইসমাইল বেগম',
    motherOccupation: 'Business',
    motherPhone: '01778-00047',
    motherNid: '2000470000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1048',
    createdAt: '2026-09-20',
    updatedAt: '2026-09-20',
    status: 'rejected',
    photo: '',
    nameEn: 'Moushumi Akter',
    nameBn: 'মৌসুমী আক্তার',
    dob: '2008-01-21',
    gender: 'Female',
    bloodGroup: 'A+',
    religion: 'Buddhism / বৌদ্ধ',
    nationality: 'Bangladeshi',
    phone: '01727-00048',
    email: 'moushumi.akter@mail.com',
    class: '8',
    section: 'D',
    roll: '48',
    academicYear: '2025-26',
    previousSchool: 'Green Valley School',
    admissionDate: '2026-09-20',
    presentAddress: 'Rajshahi Main Road, Block-V',
    permanentAddress: 'Rajshahi Dakshin',
    district: 'Rajshahi',
    fatherNameEn: 'Moulana Akter',
    fatherNameBn: 'মাওলানা আক্তার',
    fatherOccupation: 'Govt Employee',
    fatherPhone: '01769-00048',
    fatherNid: '1000480000',
    motherNameEn: 'Moushumi Begum',
    motherNameBn: 'মৌসুমী বেগম',
    motherOccupation: 'Nurse',
    motherPhone: '01779-00048',
    motherNid: '2000480000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1049',
    createdAt: '2026-09-21',
    updatedAt: '2026-09-21',
    status: 'rejected',
    photo: '',
    nameEn: 'Faruk Ahmed',
    nameBn: 'ফারুক আহমেদ',
    dob: '2008-02-22',
    gender: 'Male',
    bloodGroup: 'A-',
    religion: 'Islam / ইসলাম',
    nationality: 'Bangladeshi',
    phone: '01727-00049',
    email: 'faruk.ahmed@mail.com',
    class: '9',
    section: 'A',
    roll: '49',
    academicYear: '2025-26',
    previousSchool: 'Dhaka Public School',
    admissionDate: '2026-09-21',
    presentAddress: 'Khulna Main Road, Block-W',
    permanentAddress: 'Khulna Purba',
    district: 'Khulna',
    fatherNameEn: 'Md. Ahmed',
    fatherNameBn: 'মোঃ আহমেদ',
    fatherOccupation: 'Business',
    fatherPhone: '01770-00049',
    fatherNid: '1000490000',
    motherNameEn: 'Faruk Begum',
    motherNameBn: 'ফারুক বেগম',
    motherOccupation: 'Housewife',
    motherPhone: '01780-00049',
    motherNid: '2000490000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
  {
    id: 'ET-2026-1050',
    createdAt: '2026-09-22',
    updatedAt: '2026-09-22',
    status: 'rejected',
    photo: '',
    nameEn: 'Shamima Akter',
    nameBn: 'শামীমা আক্তার',
    dob: '2008-03-23',
    gender: 'Female',
    bloodGroup: 'B+',
    religion: 'Hinduism / হিন্দু',
    nationality: 'Bangladeshi',
    phone: '01727-00050',
    email: 'shamima.akter@mail.com',
    class: '10',
    section: 'B',
    roll: '50',
    academicYear: '2025-26',
    previousSchool: 'Scholastica',
    admissionDate: '2026-09-22',
    presentAddress: 'Barisal Main Road, Block-X',
    permanentAddress: 'Barisal Pashchim',
    district: 'Barisal',
    fatherNameEn: 'Mr. Akter',
    fatherNameBn: 'শেখ আক্তার',
    fatherOccupation: 'Service',
    fatherPhone: '01771-00050',
    fatherNid: '1000500000',
    motherNameEn: 'Shamima Begum',
    motherNameBn: 'শামীমা বেগম',
    motherOccupation: 'Teacher',
    motherPhone: '01781-00050',
    motherNid: '2000500000',
    guardianName: '',
    guardianRelation: '',
    guardianPhone: '',
  },
]

interface AdmissionState {
  students: StudentAdmission[]
  addStudent: (student: StudentAdmission) => void
  updateStudent: (id: string, data: Partial<StudentAdmission>) => void
  approveStudent: (id: string) => void
  rejectStudent: (id: string) => void
  getNextId: () => string
}

export const useAdmissionStore = create<AdmissionState>()(
  persist(
    (set, get) => ({
      students: sampleStudents,

      addStudent: (student) => set((state) => ({ students: [student, ...state.students] })),

      updateStudent: (id, data) =>
        set((state) => ({
          students: state.students.map((s) => (s.id === id ? { ...s, ...data, updatedAt: new Date().toISOString().split('T')[0] } : s)),
        })),

      approveStudent: (id) =>
        set((state) => ({
          students: state.students.map((s) =>
            s.id === id
              ? {
                  ...s,
                  status: 'approved',
                  approvedAt: new Date().toISOString().split('T')[0],
                  updatedAt: new Date().toISOString().split('T')[0],
                }
              : s
          ),
        })),

      rejectStudent: (id) =>
        set((state) => ({
          students: state.students.map((s) =>
            s.id === id ? { ...s, status: 'rejected', updatedAt: new Date().toISOString().split('T')[0] } : s
          ),
        })),

      getNextId: () => {
        const year = new Date().getFullYear()
        const count = get().students.length + 1
        const num = String(10000 + count).padStart(5, '0')
        return `ET-${year}-${num}`
      },
    }),
    {
      name: 'edutech-admissions',
      version: 2,
      migrate: (persistedState: any, version: number) => {
        if (version === 0) {
          const existing = persistedState?.students || []
          if (existing.length < 20) {
            persistedState = { ...persistedState, students: sampleStudents }
          }
        }
        const classes = useClassStore.getState().classes
        const students = (persistedState?.students || []).map((s: StudentAdmission) => ({
          ...s,
          class: normalizeClassName(s.class, classes),
        }))
        return { ...persistedState, students }
      },
    }
  )
)

export function useSessionStudents() {
  const { students } = useAdmissionStore()
  const currentSession = useClassStore((s) => s.institution.currentSession)
  return students.filter((s) => s.academicYear === currentSession)
}
