import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Teacher, Department, Subject, Designation } from '@/pages/teachers/types'

const sampleDepartments: Department[] = [
  { id: 'DEPT-001', name: 'Science', nameBn: 'বিজ্ঞান', head: 'Dr. Rafiqul Islam', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DEPT-002', name: 'Humanities', nameBn: 'মানবিক', head: 'Prof. Salma Khatun', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DEPT-003', name: 'Commerce', nameBn: 'বাণিজ্য', head: 'Md. Habibur Rahman', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DEPT-004', name: 'Languages', nameBn: 'ভাষা', head: 'Farhana Rahman', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
]

const sampleDesignations: Designation[] = [
  { id: 'DES-001', name: 'Professor', nameBn: 'অধ্যাপক', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DES-002', name: 'Associate Professor', nameBn: 'সহযোগী অধ্যাপক', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DES-003', name: 'Assistant Professor', nameBn: 'সহকারী অধ্যাপক', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DES-004', name: 'Lecturer', nameBn: 'প্রভাষক', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DES-005', name: 'Head of Department', nameBn: 'বিভাগ প্রধান', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: 'DES-006', name: 'Lab Assistant', nameBn: 'ল্যাব সহকারী', createdAt: '2026-01-01', updatedAt: '2026-01-01' },
]

const sampleSubjects: Subject[] = [
  {
    id: 'SUB-001',
    name: 'Physics',
    nameBn: 'পদার্থবিজ্ঞান',
    departmentId: 'DEPT-001',
    departmentIds: ['DEPT-001'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'SUB-002',
    name: 'Chemistry',
    nameBn: 'রসায়ন',
    departmentId: 'DEPT-001',
    departmentIds: ['DEPT-001'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'SUB-003',
    name: 'Mathematics',
    nameBn: 'গণিত',
    departmentId: 'DEPT-001',
    departmentIds: ['DEPT-001', 'DEPT-002'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'SUB-004',
    name: 'Bangla',
    nameBn: 'বাংলা',
    departmentId: 'DEPT-004',
    departmentIds: ['DEPT-004', 'DEPT-002'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'SUB-005',
    name: 'English',
    nameBn: 'ইংরেজি',
    departmentId: 'DEPT-004',
    departmentIds: ['DEPT-004', 'DEPT-001'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'SUB-006',
    name: 'History',
    nameBn: 'ইতিহাস',
    departmentId: 'DEPT-002',
    departmentIds: ['DEPT-002'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'SUB-007',
    name: 'Accounting',
    nameBn: 'হিসাববিজ্ঞান',
    departmentId: 'DEPT-003',
    departmentIds: ['DEPT-003'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'SUB-008',
    name: 'ICT',
    nameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি',
    departmentId: 'DEPT-001',
    departmentIds: ['DEPT-001', 'DEPT-002'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
]

const sampleTeachers: Teacher[] = [
  // DEPT-001 (Science) — Physics, Chemistry, Mathematics, ICT
  {
    id: 'TCH-2026-001',
    createdAt: '2026-01-10',
    updatedAt: '2026-01-10',
    status: 'active',
    photo: '',
    nameEn: 'Dr. Rafiqul Islam',
    nameBn: 'ড. রফিকুল ইসলাম',
    gender: 'Male',
    dob: '1975-03-15',
    bloodGroup: 'A+',
    religion: 'Islam',
    phone: '01711-100001',
    email: 'rafiq@edutech.com',
    address: 'Mirpur-10, Dhaka',
    nid: '1234567890123',
    emergencyPhone: '01711-100002',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-001', 'SUB-002'],
    designation: 'Head of Department',
    qualification: 'PhD in Physics',
    experience: '18 years',
    joiningDate: '2008-01-01',
    salary: 65000,
    inTime: '07:30',
    outTime: '14:30',
    fatherNameEn: 'Abdul Islam',
    fatherNameBn: 'আব্দুল ইসলাম',
    fatherPhone: '01711-111111',
    fatherNid: '1111111111111',
    motherNameEn: 'Rahima Islam',
    motherNameBn: 'রহিমা ইসলাম',
    motherPhone: '01711-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Mirpur-10, Dhaka',
  },
  {
    id: 'TCH-2026-002',
    createdAt: '2026-01-12',
    updatedAt: '2026-01-12',
    status: 'active',
    photo: '',
    nameEn: 'Tanvir Ahmed',
    nameBn: 'তানভীর আহমেদ',
    gender: 'Male',
    dob: '1982-06-20',
    bloodGroup: 'O+',
    religion: 'Islam',
    phone: '01812-200101',
    email: 'tanvir@edutech.com',
    address: 'Gulshan-2, Dhaka',
    nid: '2233445566778',
    emergencyPhone: '01812-200102',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-001'],
    designation: 'Professor',
    qualification: 'PhD in Applied Physics',
    experience: '15 years',
    joiningDate: '2011-03-01',
    salary: 58000,
    inTime: '07:30',
    outTime: '14:30',
    fatherNameEn: 'Nur Ahmed',
    fatherNameBn: 'নুর আহমেদ',
    fatherPhone: '01812-111111',
    fatherNid: '2222222222222',
    motherNameEn: 'Jesmin Ahmed',
    motherNameBn: 'জেসমিন আহমেদ',
    motherPhone: '01812-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Gulshan-2, Dhaka',
  },
  {
    id: 'TCH-2026-003',
    createdAt: '2026-01-15',
    updatedAt: '2026-01-15',
    status: 'active',
    photo: '',
    nameEn: 'Nusrat Jahan',
    nameBn: 'নুসরাত জাহান',
    gender: 'Female',
    dob: '1988-11-05',
    bloodGroup: 'B+',
    religion: 'Islam',
    phone: '01913-300201',
    email: 'nusrat@edutech.com',
    address: 'Banani-11, Dhaka',
    nid: '3344556677889',
    emergencyPhone: '01913-300202',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-002'],
    designation: 'Associate Professor',
    qualification: 'MSc in Chemistry',
    experience: '10 years',
    joiningDate: '2016-07-01',
    salary: 48000,
    inTime: '08:00',
    outTime: '15:00',
    fatherNameEn: 'Kamal Hossain',
    fatherNameBn: 'কামাল হোসেন',
    fatherPhone: '01913-111111',
    fatherNid: '3333333333333',
    motherNameEn: 'Salma Hossain',
    motherNameBn: 'সালমা হোসেন',
    motherPhone: '01913-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Banani-11, Dhaka',
  },
  {
    id: 'TCH-2026-004',
    createdAt: '2026-01-18',
    updatedAt: '2026-01-18',
    status: 'active',
    photo: '',
    nameEn: 'Md. Habibur Rahman',
    nameBn: 'মো. হাবিবুর রহমান',
    gender: 'Male',
    dob: '1980-02-28',
    bloodGroup: 'A-',
    religion: 'Islam',
    phone: '01614-400301',
    email: 'habib@edutech.com',
    address: 'Uttara-7, Dhaka',
    nid: '4455667788990',
    emergencyPhone: '01614-400302',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-003'],
    designation: 'Professor',
    qualification: 'PhD in Mathematics',
    experience: '14 years',
    joiningDate: '2012-01-15',
    salary: 55000,
    inTime: '07:45',
    outTime: '14:45',
    fatherNameEn: 'Abdur Rahman',
    fatherNameBn: 'আব্দুর রহমান',
    fatherPhone: '01614-111111',
    fatherNid: '4444444444444',
    motherNameEn: 'Anowara Rahman',
    motherNameBn: 'আনোয়ারা রহমান',
    motherPhone: '01614-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Uttara-7, Dhaka',
  },
  {
    id: 'TCH-2026-005',
    createdAt: '2026-01-20',
    updatedAt: '2026-01-20',
    status: 'active',
    photo: '',
    nameEn: 'Sabrina Akter',
    nameBn: 'সাবরিনা আক্তার',
    gender: 'Female',
    dob: '1992-08-12',
    bloodGroup: 'O+',
    religion: 'Islam',
    phone: '01515-500401',
    email: 'sabrina@edutech.com',
    address: 'Mohammadpur, Dhaka',
    nid: '5566778899001',
    emergencyPhone: '01515-500402',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-003', 'SUB-008'],
    designation: 'Lecturer',
    qualification: 'MSc in Mathematics',
    experience: '5 years',
    joiningDate: '2021-06-01',
    salary: 38000,
    inTime: '08:30',
    outTime: '15:30',
    fatherNameEn: 'Abul Kashem',
    fatherNameBn: 'আবুল কাশেম',
    fatherPhone: '01515-111111',
    fatherNid: '5555555555555',
    motherNameEn: 'Rashida Begum',
    motherNameBn: 'রশিদা বেগম',
    motherPhone: '01515-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Mohammadpur, Dhaka',
  },
  {
    id: 'TCH-2026-006',
    createdAt: '2026-01-22',
    updatedAt: '2026-01-22',
    status: 'active',
    photo: '',
    nameEn: 'Imran Hossain',
    nameBn: 'ইমরান হোসেন',
    gender: 'Male',
    dob: '1985-04-18',
    bloodGroup: 'AB+',
    religion: 'Islam',
    phone: '01716-600501',
    email: 'imran@edutech.com',
    address: 'Bashundhara, Dhaka',
    nid: '6677889900112',
    emergencyPhone: '01716-600502',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-008'],
    designation: 'Associate Professor',
    qualification: 'MSc in ICT',
    experience: '9 years',
    joiningDate: '2017-01-01',
    salary: 46000,
    inTime: '08:00',
    outTime: '15:00',
    fatherNameEn: 'Shafiqul Hossain',
    fatherNameBn: 'শফিকুল হোসেন',
    fatherPhone: '01716-111111',
    fatherNid: '6666666666666',
    motherNameEn: 'Farida Hossain',
    motherNameBn: 'ফরিদা হোসেন',
    motherPhone: '01716-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Bashundhara, Dhaka',
  },
  {
    id: 'TCH-2026-007',
    createdAt: '2026-01-25',
    updatedAt: '2026-01-25',
    status: 'on-leave',
    photo: '',
    nameEn: 'Fahim Mahmud',
    nameBn: 'ফাহিম মাহমুদ',
    gender: 'Male',
    dob: '1991-07-30',
    bloodGroup: 'B-',
    religion: 'Islam',
    phone: '01817-700601',
    email: 'fahim@edutech.com',
    address: 'Tejgaon, Dhaka',
    nid: '7788990011223',
    emergencyPhone: '01817-700602',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-002', 'SUB-001'],
    designation: 'Lecturer',
    qualification: 'MSc in Chemistry',
    experience: '4 years',
    joiningDate: '2022-07-01',
    salary: 35000,
    inTime: '08:30',
    outTime: '15:30',
    fatherNameEn: 'Mahbub Mahmud',
    fatherNameBn: 'মাহবুব মাহমুদ',
    fatherPhone: '01817-111111',
    fatherNid: '7777777777777',
    motherNameEn: 'Shirin Mahmud',
    motherNameBn: 'শিরিন মাহমুদ',
    motherPhone: '01817-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Tejgaon, Dhaka',
  },

  // DEPT-002 (Humanities) — History
  {
    id: 'TCH-2026-008',
    createdAt: '2026-02-01',
    updatedAt: '2026-02-01',
    status: 'active',
    photo: '',
    nameEn: 'Prof. Salma Khatun',
    nameBn: 'প্রো. সালমা খাতুন',
    gender: 'Female',
    dob: '1978-09-22',
    bloodGroup: 'B+',
    religion: 'Islam',
    phone: '01722-800701',
    email: 'salma@edutech.com',
    address: 'Dhanmondi, Dhaka',
    nid: '8899001122334',
    emergencyPhone: '01722-800702',
    departmentId: 'DEPT-002',
    subjectIds: ['SUB-006'],
    designation: 'Head of Department',
    qualification: 'PhD in History',
    experience: '16 years',
    joiningDate: '2010-01-01',
    salary: 58000,
    inTime: '08:00',
    outTime: '15:00',
    fatherNameEn: 'Karim Uddin',
    fatherNameBn: 'করিম উদ্দিন',
    fatherPhone: '01722-111111',
    fatherNid: '8888888888888',
    motherNameEn: 'Nasreen Uddin',
    motherNameBn: 'নাসরিন উদ্দিন',
    motherPhone: '01722-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Dhanmondi, Dhaka',
  },
  {
    id: 'TCH-2026-009',
    createdAt: '2026-02-05',
    updatedAt: '2026-02-05',
    status: 'active',
    photo: '',
    nameEn: 'Abul Kalam Azad',
    nameBn: 'আবুল কালাম আজাদ',
    gender: 'Male',
    dob: '1983-12-10',
    bloodGroup: 'A+',
    religion: 'Islam',
    phone: '01618-900801',
    email: 'kalam@edutech.com',
    address: 'Old Dhaka, Dhaka',
    nid: '9900112233445',
    emergencyPhone: '01618-900802',
    departmentId: 'DEPT-002',
    subjectIds: ['SUB-006'],
    designation: 'Associate Professor',
    qualification: 'MA in History',
    experience: '11 years',
    joiningDate: '2015-01-01',
    salary: 45000,
    inTime: '07:45',
    outTime: '14:45',
    fatherNameEn: 'Abdul Azad',
    fatherNameBn: 'আব্দুল আজাদ',
    fatherPhone: '01618-111111',
    fatherNid: '9999999999999',
    motherNameEn: 'Khadija Azad',
    motherNameBn: 'খাদিজা আজাদ',
    motherPhone: '01618-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Old Dhaka, Dhaka',
  },
  {
    id: 'TCH-2026-010',
    createdAt: '2026-02-08',
    updatedAt: '2026-02-08',
    status: 'active',
    photo: '',
    nameEn: 'Sumaiya Rahman',
    nameBn: 'সুমাইয়া রহমান',
    gender: 'Female',
    dob: '1990-05-25',
    bloodGroup: 'O-',
    religion: 'Islam',
    phone: '01919-100901',
    email: 'sumaiya@edutech.com',
    address: 'Lalmatia, Dhaka',
    nid: '1011121314151',
    emergencyPhone: '01919-100902',
    departmentId: 'DEPT-002',
    subjectIds: ['SUB-006'],
    designation: 'Lecturer',
    qualification: 'MA in History',
    experience: '6 years',
    joiningDate: '2020-01-15',
    salary: 36000,
    inTime: '08:15',
    outTime: '15:15',
    fatherNameEn: 'Abdur Rouf',
    fatherNameBn: 'আব্দুর রউফ',
    fatherPhone: '01919-111111',
    fatherNid: '1010101010101',
    motherNameEn: 'Monira Rouf',
    motherNameBn: 'মনিরা রউফ',
    motherPhone: '01919-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Lalmatia, Dhaka',
  },

  // DEPT-003 (Commerce) — Accounting
  {
    id: 'TCH-2026-011',
    createdAt: '2026-02-10',
    updatedAt: '2026-02-10',
    status: 'active',
    photo: '',
    nameEn: 'Aminul Haq',
    nameBn: 'আমিনুল হক',
    gender: 'Male',
    dob: '1979-01-08',
    bloodGroup: 'AB-',
    religion: 'Islam',
    phone: '01711-201001',
    email: 'aminul@edutech.com',
    address: 'Motijheel, Dhaka',
    nid: '1213141516171',
    emergencyPhone: '01711-201002',
    departmentId: 'DEPT-003',
    subjectIds: ['SUB-007'],
    designation: 'Head of Department',
    qualification: 'MBA in Accounting',
    experience: '15 years',
    joiningDate: '2011-01-01',
    salary: 56000,
    inTime: '07:30',
    outTime: '14:30',
    fatherNameEn: 'Abdul Haq',
    fatherNameBn: 'আব্দুল হক',
    fatherPhone: '01711-111111',
    fatherNid: '1212121212121',
    motherNameEn: 'Bushra Haq',
    motherNameBn: 'বুশরা হক',
    motherPhone: '01711-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Motijheel, Dhaka',
  },
  {
    id: 'TCH-2026-012',
    createdAt: '2026-02-12',
    updatedAt: '2026-02-12',
    status: 'active',
    photo: '',
    nameEn: 'Farhan Saeed',
    nameBn: 'ফারহান সাঈদ',
    gender: 'Male',
    dob: '1986-10-15',
    bloodGroup: 'A+',
    religion: 'Islam',
    phone: '01812-301101',
    email: 'farhan@edutech.com',
    address: 'Farmgate, Dhaka',
    nid: '1314151617181',
    emergencyPhone: '01812-301102',
    departmentId: 'DEPT-003',
    subjectIds: ['SUB-007'],
    designation: 'Associate Professor',
    qualification: 'MBA in Finance',
    experience: '8 years',
    joiningDate: '2018-01-01',
    salary: 44000,
    inTime: '08:00',
    outTime: '15:00',
    fatherNameEn: 'Saeed Ahmed',
    fatherNameBn: 'সাঈদ আহমেদ',
    fatherPhone: '01812-111111',
    fatherNid: '1313131313131',
    motherNameEn: 'Rubina Saeed',
    motherNameBn: 'রুবিনা সাঈদ',
    motherPhone: '01812-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Farmgate, Dhaka',
  },
  {
    id: 'TCH-2026-013',
    createdAt: '2026-02-14',
    updatedAt: '2026-02-14',
    status: 'inactive',
    photo: '',
    nameEn: 'Ruma Begum',
    nameBn: 'রুমা বেগম',
    gender: 'Female',
    dob: '1987-03-20',
    bloodGroup: 'B+',
    religion: 'Islam',
    phone: '01513-401201',
    email: 'ruma@edutech.com',
    address: 'Khilgaon, Dhaka',
    nid: '1415161718191',
    emergencyPhone: '01513-401202',
    departmentId: 'DEPT-003',
    subjectIds: ['SUB-007'],
    designation: 'Lecturer',
    qualification: 'BBA in Accounting',
    experience: '5 years',
    joiningDate: '2021-07-01',
    salary: 32000,
    inTime: '08:30',
    outTime: '15:30',
    fatherNameEn: 'Abdul Bari',
    fatherNameBn: 'আব্দুল বারী',
    fatherPhone: '01513-111111',
    fatherNid: '1414141414141',
    motherNameEn: 'Halima Bari',
    motherNameBn: 'হালিমা বারী',
    motherPhone: '01513-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Khilgaon, Dhaka',
  },

  // DEPT-004 (Languages) — Bangla, English
  {
    id: 'TCH-2026-014',
    createdAt: '2026-02-16',
    updatedAt: '2026-02-16',
    status: 'active',
    photo: '',
    nameEn: 'Farhana Rahman',
    nameBn: 'ফারহানা রহমান',
    gender: 'Female',
    dob: '1981-06-12',
    bloodGroup: 'AB+',
    religion: 'Islam',
    phone: '01614-501301',
    email: 'farhana@edutech.com',
    address: 'Banani, Dhaka',
    nid: '1516171819101',
    emergencyPhone: '01614-501302',
    departmentId: 'DEPT-004',
    subjectIds: ['SUB-004', 'SUB-005'],
    designation: 'Head of Department',
    qualification: 'PhD in English Literature',
    experience: '13 years',
    joiningDate: '2013-01-01',
    salary: 55000,
    inTime: '08:00',
    outTime: '15:00',
    fatherNameEn: 'Monir Rahman',
    fatherNameBn: 'মনির রহমান',
    fatherPhone: '01614-111111',
    fatherNid: '1515151515151',
    motherNameEn: 'Razia Rahman',
    motherNameBn: 'রাজিয়া রহমান',
    motherPhone: '01614-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Banani, Dhaka',
  },
  {
    id: 'TCH-2026-015',
    createdAt: '2026-02-18',
    updatedAt: '2026-02-18',
    status: 'active',
    photo: '',
    nameEn: 'Kamrul Hasan',
    nameBn: 'কামরুল হাসান',
    gender: 'Male',
    dob: '1984-09-28',
    bloodGroup: 'O+',
    religion: 'Islam',
    phone: '01715-601401',
    email: 'kamrul@edutech.com',
    address: 'Shantinagar, Dhaka',
    nid: '1617181910111',
    emergencyPhone: '01715-601402',
    departmentId: 'DEPT-004',
    subjectIds: ['SUB-005'],
    designation: 'Professor',
    qualification: 'PhD in English',
    experience: '12 years',
    joiningDate: '2014-07-01',
    salary: 52000,
    inTime: '07:45',
    outTime: '14:45',
    fatherNameEn: 'Abdur Rashid',
    fatherNameBn: 'আব্দুর রশিদ',
    fatherPhone: '01715-111111',
    fatherNid: '1616161616161',
    motherNameEn: 'Ayesha Rashid',
    motherNameBn: 'আয়েশা রশিদ',
    motherPhone: '01715-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Shantinagar, Dhaka',
  },
  {
    id: 'TCH-2026-016',
    createdAt: '2026-02-20',
    updatedAt: '2026-02-20',
    status: 'active',
    photo: '',
    nameEn: 'Nafisa Iqbal',
    nameBn: 'নাফিসা ইকবাল',
    gender: 'Female',
    dob: '1989-02-14',
    bloodGroup: 'A-',
    religion: 'Islam',
    phone: '01916-701501',
    email: 'nafisa@edutech.com',
    address: 'Elephant Road, Dhaka',
    nid: '1718191011121',
    emergencyPhone: '01916-701502',
    departmentId: 'DEPT-004',
    subjectIds: ['SUB-004'],
    designation: 'Associate Professor',
    qualification: 'MA in Bangla',
    experience: '9 years',
    joiningDate: '2017-01-15',
    salary: 45000,
    inTime: '08:15',
    outTime: '15:15',
    fatherNameEn: 'Mojibur Iqbal',
    fatherNameBn: 'মজিবুর ইকবাল',
    fatherPhone: '01916-111111',
    fatherNid: '1717171717171',
    motherNameEn: 'Hamida Iqbal',
    motherNameBn: 'হামিদা ইকবাল',
    motherPhone: '01916-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Elephant Road, Dhaka',
  },
  {
    id: 'TCH-2026-017',
    createdAt: '2026-02-22',
    updatedAt: '2026-02-22',
    status: 'active',
    photo: '',
    nameEn: 'Zahidul Haque',
    nameBn: 'জাহিদুল হক',
    gender: 'Male',
    dob: '1993-11-02',
    bloodGroup: 'B-',
    religion: 'Islam',
    phone: '01817-801601',
    email: 'zahid@edutech.com',
    address: 'Shahbagh, Dhaka',
    nid: '1819101112131',
    emergencyPhone: '01817-801602',
    departmentId: 'DEPT-004',
    subjectIds: ['SUB-005'],
    designation: 'Lecturer',
    qualification: 'MA in English',
    experience: '3 years',
    joiningDate: '2023-01-01',
    salary: 32000,
    inTime: '08:30',
    outTime: '15:30',
    fatherNameEn: 'Abdul Haque',
    fatherNameBn: 'আব্দুল হক',
    fatherPhone: '01817-111111',
    fatherNid: '1818181818181',
    motherNameEn: 'Razia Haque',
    motherNameBn: 'রাজিয়া হক',
    motherPhone: '01817-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Shahbagh, Dhaka',
  },
  {
    id: 'TCH-2026-018',
    createdAt: '2026-02-24',
    updatedAt: '2026-02-24',
    status: 'active',
    photo: '',
    nameEn: 'Taslima Nasreen',
    nameBn: 'তসলিমা নাসরিন',
    gender: 'Female',
    dob: '1986-07-19',
    bloodGroup: 'O+',
    religion: 'Islam',
    phone: '01518-901701',
    email: 'taslima@edutech.com',
    address: 'Mirpur-10, Dhaka',
    nid: '1910111213141',
    emergencyPhone: '01518-901702',
    departmentId: 'DEPT-004',
    subjectIds: ['SUB-004'],
    designation: 'Lecturer',
    qualification: 'MA in Bangla Literature',
    experience: '7 years',
    joiningDate: '2019-06-01',
    salary: 37000,
    inTime: '08:00',
    outTime: '15:00',
    fatherNameEn: 'Abdur Rashid',
    fatherNameBn: 'আব্দুর রশিদ',
    fatherPhone: '01518-111111',
    fatherNid: '1919191919191',
    motherNameEn: 'Khadija Rashid',
    motherNameBn: 'খাদিজা রশিদ',
    motherPhone: '01518-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Mirpur-10, Dhaka',
  },

  // Additional teachers for mix
  {
    id: 'TCH-2026-019',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-01',
    status: 'inactive',
    photo: '',
    nameEn: 'Shariful Islam',
    nameBn: 'শরিফুল ইসলাম',
    gender: 'Male',
    dob: '1983-05-05',
    bloodGroup: 'A+',
    religion: 'Islam',
    phone: '01619-101801',
    email: 'sharif@edutech.com',
    address: 'Wari, Dhaka',
    nid: '2011121314151',
    emergencyPhone: '01619-101802',
    departmentId: 'DEPT-001',
    subjectIds: ['SUB-003', 'SUB-001'],
    designation: 'Lecturer',
    qualification: 'MSc in Mathematics',
    experience: '6 years',
    joiningDate: '2020-01-01',
    salary: 36000,
    inTime: '08:15',
    outTime: '15:15',
    fatherNameEn: 'Mohammad Islam',
    fatherNameBn: 'মোহাম্মদ ইসলাম',
    fatherPhone: '01619-111111',
    fatherNid: '2012121212121',
    motherNameEn: 'Fatema Islam',
    motherNameBn: 'ফাতেমা ইসলাম',
    motherPhone: '01619-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Wari, Dhaka',
  },
  {
    id: 'TCH-2026-020',
    createdAt: '2026-03-05',
    updatedAt: '2026-03-05',
    status: 'on-leave',
    photo: '',
    nameEn: 'Afia Mostafa',
    nameBn: 'আফিয়া মোস্তফা',
    gender: 'Female',
    dob: '1991-12-28',
    bloodGroup: 'B+',
    religion: 'Islam',
    phone: '01715-201901',
    email: 'afia@edutech.com',
    address: 'Hazaribagh, Dhaka',
    nid: '2112131415161',
    emergencyPhone: '01715-201902',
    departmentId: 'DEPT-002',
    subjectIds: ['SUB-006'],
    designation: 'Assistant Lecturer',
    qualification: 'BA in History',
    experience: '2 years',
    joiningDate: '2024-01-15',
    salary: 28000,
    inTime: '08:30',
    outTime: '15:30',
    fatherNameEn: 'Mostafa Kamal',
    fatherNameBn: 'মোস্তফা কামাল',
    fatherPhone: '01715-111111',
    fatherNid: '2113131313131',
    motherNameEn: 'Nargis Mostafa',
    motherNameBn: 'নার্গিস মোস্তফা',
    motherPhone: '01715-222222',
    guardianName: '',
    guardianPhone: '',
    guardianRelation: '',
    parentAddress: 'Hazaribagh, Dhaka',
  },
]

export type AttendanceStatus = 'present' | 'absent' | 'on-leave'

export interface PunchRecord {
  time: string
  type: 'in' | 'out'
}

export interface DayAttendance {
  status: AttendanceStatus
  punches: PunchRecord[]
}

// Generate demo attendance for last 28 days with punch times
function generateDemoAttendance(): Record<string, Record<string, DayAttendance>> {
  const att: Record<string, Record<string, DayAttendance>> = {}
  const teacherIds = sampleTeachers.map((t) => t.id)
  const inTimes = [
    '07:20',
    '07:25',
    '07:28',
    '07:30',
    '07:32',
    '07:35',
    '07:38',
    '07:40',
    '07:42',
    '07:45',
    '07:50',
    '07:55',
    '08:00',
    '08:01',
    '08:05',
  ]
  const now = new Date()
  for (let i = 0; i <= 28; i++) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    const day = d.getDay()
    if (day === 0) continue
    const dateStr = d.toISOString().split('T')[0]
    const dayAtt: Record<string, DayAttendance> = {}
    teacherIds.forEach((tid) => {
      const rand = Math.random()
      let status: AttendanceStatus
      const teacher = sampleTeachers.find((t) => t.id === tid)
      if (teacher?.status === 'on-leave') {
        status = rand < 0.3 ? 'present' : rand < 0.5 ? 'on-leave' : 'absent'
      } else {
        status = rand < 0.85 ? 'present' : rand < 0.95 ? 'absent' : 'on-leave'
      }
      const punches: PunchRecord[] = []
      if (status === 'present') {
        const inTime = inTimes[Math.floor(Math.random() * inTimes.length)]
        const outHour = 14 + Math.floor(Math.random() * 2)
        const outMin = Math.floor(Math.random() * 60)
        const outTime = `${String(outHour).padStart(2, '0')}:${String(outMin).padStart(2, '0')}`
        punches.push({ time: inTime, type: 'in' })
        if (Math.random() > 0.3)
          punches.push({
            time: `${String(10 + Math.floor(Math.random() * 2)).padStart(2, '0')}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}`,
            type: 'out',
          })
        if (Math.random() > 0.3)
          punches.push({
            time: `${String(11 + Math.floor(Math.random() * 2)).padStart(2, '0')}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}`,
            type: 'in',
          })
        punches.push({ time: outTime, type: 'out' })
      }
      dayAtt[tid] = { status, punches }
    })
    att[dateStr] = dayAtt
  }
  return att
}

interface TeacherState {
  teachers: Teacher[]
  departments: Department[]
  subjects: Subject[]
  designations: Designation[]
  attendance: Record<string, Record<string, DayAttendance>>
  addTeacher: (teacher: Teacher) => void
  updateTeacher: (id: string, data: Partial<Teacher>) => void
  deleteTeacher: (id: string) => void
  getNextTeacherId: () => string
  addDepartment: (dept: Department) => void
  updateDepartment: (id: string, data: Partial<Department>) => void
  deleteDepartment: (id: string) => void
  addSubject: (sub: Subject) => void
  updateSubject: (id: string, data: Partial<Subject>) => void
  deleteSubject: (id: string) => void
  addDesignation: (des: Designation) => void
  updateDesignation: (id: string, data: Partial<Designation>) => void
  deleteDesignation: (id: string) => void
  markAttendance: (date: string, teacherId: string, status: AttendanceStatus) => void
  markAllPresent: (date: string) => void
  getAttendanceStats: (date: string) => { present: number; absent: number; onLeave: number }
}

export const useTeacherStore = create<TeacherState>()(
  persist(
    (set, get) => ({
      teachers: sampleTeachers,
      departments: sampleDepartments,
      subjects: sampleSubjects,
      designations: sampleDesignations,
      attendance: generateDemoAttendance(),

      addTeacher: (teacher) => set((state) => ({ teachers: [teacher, ...state.teachers] })),

      updateTeacher: (id, data) =>
        set((state) => ({
          teachers: state.teachers.map((t) => (t.id === id ? { ...t, ...data, updatedAt: new Date().toISOString().split('T')[0] } : t)),
        })),

      deleteTeacher: (id) => set((state) => ({ teachers: state.teachers.filter((t) => t.id !== id) })),

      getNextTeacherId: () => {
        const year = new Date().getFullYear()
        const count = get().teachers.length + 1
        const num = String(100 + count).padStart(3, '0')
        return `TCH-${year}-${num}`
      },

      addDepartment: (dept) => set((state) => ({ departments: [...state.departments, dept] })),

      updateDepartment: (id, data) =>
        set((state) => ({
          departments: state.departments.map((d) =>
            d.id === id ? { ...d, ...data, updatedAt: new Date().toISOString().split('T')[0] } : d
          ),
        })),

      deleteDepartment: (id) => set((state) => ({ departments: state.departments.filter((d) => d.id !== id) })),

      addSubject: (sub) => set((state) => ({ subjects: [...state.subjects, sub] })),

      updateSubject: (id, data) =>
        set((state) => ({
          subjects: state.subjects.map((s) => (s.id === id ? { ...s, ...data, updatedAt: new Date().toISOString().split('T')[0] } : s)),
        })),

      deleteSubject: (id) => set((state) => ({ subjects: state.subjects.filter((s) => s.id !== id) })),

      addDesignation: (des) => set((state) => ({ designations: [...state.designations, des] })),

      updateDesignation: (id, data) =>
        set((state) => ({
          designations: state.designations.map((d) =>
            d.id === id ? { ...d, ...data, updatedAt: new Date().toISOString().split('T')[0] } : d
          ),
        })),

      deleteDesignation: (id) => set((state) => ({ designations: state.designations.filter((d) => d.id !== id) })),

      markAttendance: (date, teacherId, status) =>
        set((state) => ({
          attendance: {
            ...state.attendance,
            [date]: {
              ...(state.attendance[date] || {}),
              [teacherId]: { status, punches: state.attendance[date]?.[teacherId]?.punches || [] },
            },
          },
        })),

      markAllPresent: (date) =>
        set((state) => {
          const allPresent: Record<string, DayAttendance> = {}
          state.teachers.forEach((t) => {
            allPresent[t.id] = { status: 'present', punches: [] }
          })
          return {
            attendance: {
              ...state.attendance,
              [date]: allPresent,
            },
          }
        }),

      getAttendanceStats: (date) => {
        const dayAtt = get().attendance[date] || {}
        const teachers = get().teachers.filter((t) => t.status === 'active')
        let present = 0,
          absent = 0,
          onLeave = 0
        teachers.forEach((t) => {
          const d = dayAtt[t.id]
          const s = d?.status
          if (s === 'present') present++
          else if (s === 'absent') absent++
          else if (s === 'on-leave') onLeave++
        })
        return { present, absent, onLeave }
      },
    }),
    {
      name: 'edutech-teachers',
      version: 2,
      migrate: (persistedState: any, version: number) => {
        if (version === 0) {
          const existing = persistedState?.teachers || []
          if (existing.length < 7) {
            return {
              ...persistedState,
              teachers: sampleTeachers,
              departments: sampleDepartments,
              subjects: sampleSubjects,
              designations: sampleDesignations,
            }
          }
        }
        if (version === 1) {
          return { ...persistedState, designations: persistedState?.designations || sampleDesignations }
        }
        return persistedState
      },
    }
  )
)
